--All SQL used are documented in this file.

CREATE TABLE IF NOT EXISTS movies (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "title" TEXT NOT NULL,
    "genre" TEXT NOT NULL,
    "year" INTEGER NOT NULL,
    "director" TEXT NOT NULL,
    "rating" REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "firstname" TEXT NOT NULL,
    "lastname" TEXT NOT NULL,
    "email" TEXT NOT NULL UNIQUE,
    "username" TEXT NOT NULL UNIQUE,
    "address" TEXT NOT NULL,
    "credit_card" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS schedule (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "movie_id" INTEGER,
    "time" DATETIME,
    "room" INTEGER,
    FOREIGN KEY (movie_id) REFERENCES movies(id)
);

--The IDs should be autoincremented. 
--All data are from IMDB.
INSERT INTO movies (title, genre, year, director, rating) 
VALUES 
('Shrek', 'Comedy', 2001, 'Andrew Adamson', 7.9),
('Trolls', 'Musical', 2016, 'Mike Mitchell', 6.4),
('Puss In Boots: The Last Wish', 'Adventure', 2022, 'Mark Swift', 7.9),
('The Boss Baby', 'Comedy', 2017, 'Tom McGrath', 6.3),
('Kung Fu Panda', 'Action', 2008, 'John Stevenson', 7.6),
('How to Train Your Dragon', 'Fantasy', 2010, 'Chris Sanders', 8.1),
('Puss in Boots', 'Action', 2011, 'Chris Miller', 6.6),
('Turbo', 'Sports', 2013, 'David Soren', 6.4),
('How to Train Your Dragon 2', 'Fantasy', 2014, 'Dean DeBlois', 7.8),
('Penguins of Madagascar', 'Action', 2014, 'Eric Darnell', 6.6),
('How to Train Your Dragon 3', 'Fantasy', 2019, 'Dean DeBlois', 7.4),
('The Super Mario Bros. Movie', 'Adventure', 2022, 'Aaron Horvath', 7.8),
('Cars', 'Sports', 2006, 'John Lasseter', 7.2),
('Spirited Away', 'Fantasy', 2001, 'Hayao Miyazaki', 8.6),
('The Lion King', 'Drama', 2019, 'Jon Favreau', 6.8),
('Moana', 'Fantasy', 2016, 'Ron Clements', 7.6),
('Ratatouille', 'Comedy', 2007, 'Brad Bird', 8.1),
('Toy Story', 'Fantasy', 1995, 'John Lasseter', 8.3),
('WALL-E', 'Sci-fi', 2008, 'Andrew Stanton', 8.4),
('Minions', 'Comedy', 2015, 'Kyle Balda', 6.4);

--Values are randomly generated by ChatGPT
INSERT INTO schedule (movie_id, time, room) VALUES
    (1, '2023-04-06 12:00:00', 1),
    (9, '2023-04-06 15:00:00', 2),
    (13, '2023-04-06 18:00:00', 3),
    (7, '2023-04-07 12:00:00', 2),
    (15, '2023-04-07 15:00:00', 3),
    (18, '2023-04-07 18:00:00', 1),
    (5, '2023-04-08 12:00:00', 3),
    (11, '2023-04-08 15:00:00', 1),
    (16, '2023-04-08 18:00:00', 2),
    (6, '2023-04-09 12:00:00', 1),
    (19, '2023-04-09 15:00:00', 2),
    (4, '2023-04-09 18:00:00', 3),
    (2, '2023-04-10 12:00:00', 2),
    (17, '2023-04-10 15:00:00', 3),
    (10, '2023-04-10 18:00:00', 1),
    (3, '2023-04-11 12:00:00', 3),
    (8, '2023-04-11 15:00:00', 1),
    (14, '2023-04-11 18:00:00', 2),
    (20, '2023-04-12 12:00:00', 1),
    (12, '2023-04-12 15:00:00', 2),
    (1, '2023-04-12 18:00:00', 3),
    (9, '2023-04-13 12:00:00', 2),
    (13, '2023-04-13 15:00:00', 3),
    (7, '2023-04-13 18:00:00', 1),
    (15, '2023-04-14 12:00:00', 3),
    (18, '2023-04-14 15:00:00', 1),
    (5, '2023-04-14 18:00:00', 2),
    (11, '2023-04-15 12:00:00', 1),
    (16, '2023-04-15 15:00:00', 2),
    (6, '2023-04-15 18:00:00', 3),
    (19, '2023-04-16 12:00:00', 2),
    (4, '2023-04-16 15:00:00', 3),
    (2, '2023-04-16 18:00:00', 1),
    (17, '2023-04-17 12:00:00', 3);
